### ISSUE TITLE
Adding documentation to a slash command for user convenience

### ISSUE THREAD

**Issue by gnsals0904** [gnsals0904/bbangddoa#5]
Adding documentation to a slash command for user convenience

- [x] To add a help command
- [ ] To change and register various commands as slash commands

**Comment by gnsals0904** [comment]
Added !help command without changing to slash command

**Comment by Verssae** [comment]
No more updates to migrate to the slash command ? 😢

**Comment by gnsals0904** [comment]
I'm ready to do it whenever you want. but I am currently planning a new project.
